M3 refactor good practices
shirosweets/Proyecto-Bedu-Naranja-Kotlin pull request #24
Opened 2021-10-21 07:26 UTC by AgustinMDominguez

👁️

2021-10-21 13:05 UTC, shirosweets requested changes
@AgustinMDominguez 
- **LogOut** no cierra sesión
- Home del **Shop** no anda
- **Update** de la ubicación actual crashea la app

2021-10-22 00:08 UTC, RicardoLopez9908 commented
Los test unitarios disminuyeron y no se realizan comprobaciones de contraseña con mínimo 8 caracteres.

2021-10-22 12:23 UTC, shirosweets commented
@AgustinMDominguez
- [x] Actualizar la branch con `main`,
- [x] crear los issues correspondientes a lo implementado, linkearlos a la PR y
- [x] mergear a `main`

_Mencionarme cuando estos pasos estén hechos_

2021-10-22 14:15 UTC, AgustinMDominguez commented
Lineamientos

 - Deben existir al menos 5 test unitarios que corran en la JVM, sin dependencia del framework de Android. Si no existe una clase que pueda ser testeada, crearla.
 - Deben existir al menos 2 tests que involucren el uso del framework de android en un test unitario local (no instrumentado).
 - Debe de existir al menos 4 tests de integración instrumentados (funciones simples como interactuar con la UI y verificar que una acción esté funcionando correctamente).

Tips:

 - Escribe primero los tests antes que el código, esto asegurará que la calidad de la funcionalidad desarrollada sea alta y sabremos que el código está completo cuando pase el test.
 - Desarrolla primero los tests unitarios, después los de integración y finalmente los de end-to-end.

2021-10-22 15:30 UTC, AgustinMDominguez commented
@RicardoLopez9908 ahi agregué 2 test más. Podemos agregar más después pero con esto se cumple el postwork

2021-10-22 15:38 UTC, AgustinMDominguez commented
@shirosweets @RicardoLopez9908

2021-10-22 15:39 UTC, shirosweets approved these changes

2021-10-22 15:40 UTC, RicardoLopez9908 commented
Genial! Están muy buenos los tests de consumo de Api

2021-10-22 15:41 UTC, RicardoLopez9908 approved these changes

2021-10-22 15:42 UTC, merged